### PR TITLE
methods to charge the connected acc balance and pay it

### PR DESCRIPTION
**Pull request by hbakouane**

### CODE REVIEW

**Comment by ExpDev07** [comment]
Hello and thank you so much for wanting to contribute! 

This looks good! But make sure to follow the general coding style, such as "ManageVendor" should become "ManagesVendor". Additionally use camelCase for method parameters, and add some missing white space here and there.

😃

**Comment by hbakouane** [comment]
Okay Sure

**Comment by hbakouane** [comment]
Can you tell me if this will be merged? Thanks

**Review by ExpDev07 — CHANGES_REQUESTED** [review]
If you could please change "acc" to the full "account" everywhere, then I will merge! Thank you!

**Comment by ExpDev07** [comment]
Hey, I was not completely satisfied with the implementation. I took some time to improve on it, and the code in general. The PR does not introduce any breaking changes.

https://github.com/ExpDev07/laravel-cashier-stripe-connect/pull/9

**Pull request closed without merging**
